# Site settings
title: 'xflops'
description: "Serverless runtime with Flame for Security, Performance and Cost."
url: 'https://xflops.io'
baseurl: ''

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/
  blog:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "blog"
      author: "xflops Team"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
nav:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/overview/
    children:
      - title: Getting Started
        url: /docs/getting-started/
      - title: User Guide
        url: /docs/user-guide/
      - title: API Reference
        url: /docs/api-reference/
  - title: Blog
    url: /blog/
  - title: GitHub
    url: https://github.com/xflops/flame
    external: true

# Social links
social:
  - name: GitHub
    url: https://github.com/xflops
  - name: Slack
    url: http://xflops.slack.com

# Author
author:
  name: 'XFLOPS'
  email: 'support@xflops.io'

# Logo
logo: "/images/flame-logo.png"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/